### ISSUE TITLE
Resoruces getting outdated

### ISSUE THREAD

**Issue by boyd-boyd** [olexale/flutter_roadmap#16]
It's being a long time and the resources aren't updated, i am to new app development and following this roadmap so i would be very helpful if the resources section get a fresh new update

**Comment by olexale** [comment]
Hi @boyd-boyd,

The resources that are mentioned in README are intentionally universal. I've briefly reviewed them, and the only change I would make now is to replace Chopper with Retrofit. But that's my personal preference.

Do you find any particular resource that needs to be updated?

**Comment by boyd-boyd** [comment]
Hi @olexale , i was particular talking about the persistent and database section, ( the hive official documentation suggest using ISAR db instead of hive (which is written by the same person(simon) ) and the packages in persistent section localStorage and flutter_keychain are not updated from past 22 months and 6 months.

I request for updating the resources ( because i'm new and don't know the possible options and which are good at current timeline), I do agree your opinion that most of the roadmap is universal and doesn't need to be changed frequently.

**Comment by olexale** [comment]
I've updated the links and updated the roadmap in general. Thanks for pointing out this issue! Feel free to re-open this issue or create a new one if you spot any other problems.
Kind regards
